services:
  # kafka-zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   container_name: kafka-zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #   attach: false

  # # reachable on 9092 from the host and on 29092 from inside docker compose
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka
  #   depends_on:
  #     - kafka-zookeeper
  #   ports:
  #     - '9092:9092'
  #   expose:
  #     - '29092'
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
  #     KAFKA_MIN_INSYNC_REPLICAS: '1'
  #   attach: false

  # kafka-init:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka-init
  #   depends_on:
  #     - kafka
  #   entrypoint: [ '/bin/sh', '-c' ]
  #   command: |
  #     "
  #     # blocks until kafka is reachable
  #     kafka-topics --bootstrap-server kafka:29092 --list

  #     # Motor Control Topics
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.motor.yaw --replication-factor 1 --partitions 3
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.motor.tilt --replication-factor 1 --partitions 3
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.motor.forward --replication-factor 1 --partitions 3
      
  #     # Sensor Topics
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.sensor.camera --replication-factor 1 --partitions 3
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.sensor.position --replication-factor 1 --partitions 3
      
  #     # System Topics
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.system.status --replication-factor 1 --partitions 2
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.system.logs --replication-factor 1 --partitions 2
      
  #     # Control Topics
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.control.commands --replication-factor 1 --partitions 3
  #     kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scant.control.responses --replication-factor 1 --partitions 3

  #     echo -e 'Successfully created the following topics:'
  #     kafka-topics --bootstrap-server kafka:29092 --list
  #     "
  #   attach: false

  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8081:8080
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: scant-local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #   attach: false
    # volumes:
    #   - ./config.yml:/etc/kafkaui/dynamic_config.yaml

  scant-ui:
    container_name: scant-ui
    build:
      context: ./scant
      dockerfile: Dockerfile-ui
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    ports:
      - 8080:8080
      - 8765:8765
    volumes:
      - ./scant:/app
    command: ["python3","-u","/app/scripts/ui.py"]

  scant-camera:
    container_name: scant-camera
    depends_on:
      - scant-ui
    build:
      context: ./scant
      dockerfile: Dockerfile-camera
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    privileged: true # Required for USB camera access/ passthrough from host
    volumes:
      - ./scant:/app
      - /etc/udev/rules.d:/etc/udev/rules.d:ro  # Mount host's udev rules
      - /run/udev:/run/udev:ro  # Mount host's udev runtime
    command: ["python3","-u","/app/scripts/camera.py"]

